//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSID.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GSID.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ buộc phải nhập..
        /// </summary>
        public static string AddressRequiredCustomerViewModel {
            get {
                return ResourceManager.GetString("AddressRequiredCustomerViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang đầu.
        /// </summary>
        public static string AgentPagePagingFirst {
            get {
                return ResourceManager.GetString("AgentPagePagingFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang cuối.
        /// </summary>
        public static string AgentPagePagingLast {
            get {
                return ResourceManager.GetString("AgentPagePagingLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếp.
        /// </summary>
        public static string AgentPagePagingNext {
            get {
                return ResourceManager.GetString("AgentPagePagingNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lùi.
        /// </summary>
        public static string AgentPagePagingPrev {
            get {
                return ResourceManager.GetString("AgentPagePagingPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khu vực.
        /// </summary>
        public static string AgentPageSelectAreaName {
            get {
                return ResourceManager.GetString("AgentPageSelectAreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quận/Huyện.
        /// </summary>
        public static string AgentPageSelectDistrictName {
            get {
                return ResourceManager.GetString("AgentPageSelectDistrictName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉnh/thành.
        /// </summary>
        public static string AgentPageSelectProvinceName {
            get {
                return ResourceManager.GetString("AgentPageSelectProvinceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng kiểm tra lại thông tin..
        /// </summary>
        public static string ContactUsFormMesageError {
            get {
                return ResourceManager.GetString("ContactUsFormMesageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm ơn bạn đã liên hệ với chúng tôi!.
        /// </summary>
        public static string ContactUsFormMesageSuccess {
            get {
                return ResourceManager.GetString("ContactUsFormMesageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        public static string ContactUsFormTitleSuccess {
            get {
                return ResourceManager.GetString("ContactUsFormTitleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quận/huyện buộc phải nhập..
        /// </summary>
        public static string DistrictIdRequiredCustomerViewModel {
            get {
                return ResourceManager.GetString("DistrictIdRequiredCustomerViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng nhập đúng định dạng email..
        /// </summary>
        public static string EmailRegularExpressionCustomerViewModel {
            get {
                return ResourceManager.GetString("EmailRegularExpressionCustomerViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email buộc phải nhập..
        /// </summary>
        public static string EmailRequiredCustomerViewModel {
            get {
                return ResourceManager.GetString("EmailRequiredCustomerViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên buộc phải nhập..
        /// </summary>
        public static string NameRequiredCustomerViewModel {
            get {
                return ResourceManager.GetString("NameRequiredCustomerViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại buộc phải nhập..
        /// </summary>
        public static string PhoneNumberRequiredCustomerViewModel {
            get {
                return ResourceManager.GetString("PhoneNumberRequiredCustomerViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉnh/thành phố buộc phải nhập..
        /// </summary>
        public static string ProvinceIdRequiredCustomerViewModel {
            get {
                return ResourceManager.GetString("ProvinceIdRequiredCustomerViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng buộc phải nhập..
        /// </summary>
        public static string QualityRequiredCustomerViewModel {
            get {
                return ResourceManager.GetString("QualityRequiredCustomerViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng kiểm tra lại thông tin..
        /// </summary>
        public static string RequestAQuoteMessageError {
            get {
                return ResourceManager.GetString("RequestAQuoteMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm ơn Quý Khách đã đặt đơn hàng &lt;br/&gt;Yêu cầu đặt hàng của Quý Khách đã gửi thành công đến Bộ phận kinh doanh của SuperStone.&lt;br/&gt;Chúng tôi sẽ liên hệ Quý Khách trong thời gian sớm nhất.&lt;br/&gt;Xin cảm ơn!.
        /// </summary>
        public static string RequestAQuoteMessageSuccess {
            get {
                return ResourceManager.GetString("RequestAQuoteMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        public static string RequestAQuoteTitleError {
            get {
                return ResourceManager.GetString("RequestAQuoteTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        public static string RequestAQuoteTitleSuccess {
            get {
                return ResourceManager.GetString("RequestAQuoteTitleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xử lý....
        /// </summary>
        public static string RequestFormProcessing {
            get {
                return ResourceManager.GetString("RequestFormProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng kiểm tra lại thông tin..
        /// </summary>
        public static string RequestRegisterAgentFormMessageError {
            get {
                return ResourceManager.GetString("RequestRegisterAgentFormMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu Đăng ký trở thành Đại Lý SUPERSTONE đã gửi thành công!.
        /// </summary>
        public static string RequestRegisterAgentFormMessageSuccess {
            get {
                return ResourceManager.GetString("RequestRegisterAgentFormMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        public static string RequestRegisterAgentFormTitleSuccess {
            get {
                return ResourceManager.GetString("RequestRegisterAgentFormTitleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng kiểm tra lại thông tin..
        /// </summary>
        public static string RequestSubscriptionFormMessageError {
            get {
                return ResourceManager.GetString("RequestSubscriptionFormMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu đăng ký Email thành công!.
        /// </summary>
        public static string RequestSubscriptionFormMessageSuccess {
            get {
                return ResourceManager.GetString("RequestSubscriptionFormMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        public static string RequestSubscriptionFormTitleSuccess {
            get {
                return ResourceManager.GetString("RequestSubscriptionFormTitleSuccess", resourceCulture);
            }
        }
    }
}
